Repository MonalikaPatnaik/UMatter, pull requests merged in 2023-06, with the labels that each got.

#600 Off centre footer #550
  src/Components/Footer/index.js
Labels: level1

#601 Issue #588 has been fixed
  src/Components/Footer/FooterElements.js
Labels: level1

#605 resolved pswrd position button
  src/Components/Signin/index.js
Labels: level2

#608 Removed dark mode button from blogs page
  src/Components/Blogs/index.js
Labels: gssoc23, level1

#612 adding validation to signup page
  src/Components/Signup/index.js
Labels: gssoc23, level2

#619 adding footer to signup page
  src/Components/Signup/SignupElements.js
  src/pages/signup.js
Labels: gssoc23, level1

#688 Add some changes in some file
  src/Components/Footer/FooterElements.js
  src/Components/Footer/index.js
  src/Components/Signup/index.js
Labels: gssoc23, level1

#797 Added the blog related to the medical chatbot by Parmesh Bhatt
  src/Components/Blogs/index.js
Labels: gssoc23, level1

#794 Input field is now visible in light mode
  src/Components/Blogs/index.js
Labels: gssoc23, level1

#878 Removed bug and added animation in testimonial section
  package.json
  src/Components/Testimonials/ProductForSlider.js
  src/Components/Testimonials/ProductSlider.css
  src/Components/Testimonials/Swiper.css
  src/Components/Testimonials/TestimonialsElements.js
  src/Components/Testimonials/index.js
Labels: gssoc23, level2

#892 About page revamp
  package.json
  src/Components/InfoSection/InfoElements.js
  src/Components/InfoSection/index.js
  src/Components/Services/ServicesElements.js
  src/Components/Testimonials/Swiper.css
  src/Components/Testimonials/TestimonialsElements.js
Labels: gssoc23, level2

#903 Add captcha verification on the signup page
  src/Components/Signup/Captcha.js
  src/Components/Signup/SignupElements.js
  src/Components/Signup/index.js
  src/images/captcha_Bg.jpg
Labels: gssoc23, level2
